### ISSUE TITLE
Issue with Playroom SDK

### ISSUE THREAD

**Issue by jakerator** [grayhatdevelopers/next-ts-multiplayer-game#1]
The app is returning errors like " ReactDOM.render is no longer supported in React 18" in console. 
Also "ReferenceError: window is not defined" in nodejs.
It seams Playroom SDK is not compatible wiht latest NextJS. I'm having the same issues integrating it...

**Comment by tommasoromano** [comment]
Same issue here! Any solution?

**Comment by SaadBazaz** [comment]
Hello guys @tommasoromano @jakerator ,
Sorry for not seeing this earlier. I was able to reproduce the problem by running `pnpm build`
I've resolved it in the latest version. 

Please run `npx create-multiplayer-game@latest --template next-ts` to generate another template again.
